/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aposta;

import javax.swing.JOptionPane;

public class LotoMania extends javax.swing.JFrame {
    public LotoMania() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLresultado = new javax.swing.JLabel();
        jTFnumero = new javax.swing.JTextField();
        jBgerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Escolha a quantidade de numeros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 100, 270, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Numeros sorteados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 250, 160, 22);

        jLresultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jLresultado);
        jLresultado.setBounds(10, 300, 360, 20);

        jTFnumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTFnumero);
        jTFnumero.setBounds(120, 140, 90, 39);

        jBgerar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBgerar.setText("Gerar");
        jBgerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgerarActionPerformed(evt);
            }
        });
        getContentPane().add(jBgerar);
        jBgerar.setBounds(120, 200, 93, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("50 a 80 numeros");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 200, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Loto Mania");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 20, 270, 60);

        setSize(new java.awt.Dimension(398, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBgerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgerarActionPerformed
    int vet[];  
    int x, numero, p, k;
    byte encontrou;
    int quantosNumeros = Integer.parseInt(jTFnumero.getText());
        vet = new int[quantosNumeros];        
        p = 0; // primeira posição do vetor
        for (x=1; x <= quantosNumeros; x++) { 
            numero = (int) (Math.random() * 100) + 1;
            encontrou = 0;
                for (k = 0; k < p; k++) {
                    if ( numero == vet[k]) {  
                        x = x - 1;
                        encontrou++; 
                    }
                }    
            if (encontrou == 0) {
                vet[p] = numero;
                p = p + 1 ; //p++
            }
        }
            for (k = 0 ; k < quantosNumeros; k++) { 
            jLresultado.setText(vet[k] + " " + jLresultado.getText());
        }
    }//GEN-LAST:event_jBgerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotoMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotoMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotoMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotoMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LotoMania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBgerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JTextField jTFnumero;
    // End of variables declaration//GEN-END:variables
}
